In [1]:
import numpy as np

In [2]:
li=[1,2,3,4,5]

In [4]:
x=np.array(li)

In [5]:
x

array([1, 2, 3, 4, 5])

In [9]:
type(x)

numpy.ndarray

In [6]:
import pandas as pd

In [10]:
y=np.array([1,nan,2,3,4,5])

NameError: name 'nan' is not defined

In [8]:
y=np.array(1,None,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [11]:
y=np.array([1,None,2,3,4,5])

In [12]:
y

array([1, None, 2, 3, 4, 5], dtype=object)

In [14]:
dtype(y)

NameError: name 'dtype' is not defined

In [15]:
type(y)

numpy.ndarray

In [16]:
datatype(y)

NameError: name 'datatype' is not defined

In [17]:
y.datatype()

AttributeError: 'numpy.ndarray' object has no attribute 'datatype'

In [18]:
y.dtype()

TypeError: 'numpy.dtype[object_]' object is not callable

In [19]:
y.dtype

dtype('O')

In [20]:
y

array([1, None, 2, 3, 4, 5], dtype=object)

In [22]:
z=[1,np.nan,2,3,4,5]

In [23]:
z

[1, nan, 2, 3, 4, 5]

In [31]:
type(z)

list

In [33]:
np.array(z)

array([ 1., nan,  2.,  3.,  4.,  5.])

In [34]:
z

[1, nan, 2, 3, 4, 5]

In [24]:
a=pd.Series(range(5))

In [30]:
a    #int type

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
dtype: float64

In [26]:
a[3]=np.nan

In [29]:
a  #it changed to float data type

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
dtype: float64

type class

1. floating ----- no change-------np.nan
2. object --------no change-------np.nan or None
3. integer -------cast to float64-----np.nan
4. boolean-------cast to object -----None or np.nan

In [37]:
###########3FOCUS ON DATA TYPE AND CHANGE

In [35]:
q=pd.Series([1,None,2,3,4])

In [36]:
q

0    1.0
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64

In [38]:
q[3]=np.nan

In [39]:
q

0    1.0
1    NaN
2    2.0
3    NaN
4    4.0
dtype: float64

In [40]:
w=pd.Series(range(5),dtype=object)

In [41]:
w

0    0
1    1
2    2
3    3
4    4
dtype: object

In [42]:
w[2]=None

In [43]:
w

0       0
1       1
2    None
3       3
4       4
dtype: object

In [44]:
w=pd.Series(range(5),dtype=bool)

In [45]:
w

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [46]:
w[2]=None

In [47]:
w

0    False
1     True
2      NaN
3     True
4     True
dtype: object

In [48]:
1+nan

NameError: name 'nan' is not defined

In [49]:
1+None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [50]:
1+np.nan

nan

In [51]:
1*np.nan

nan

In [52]:
np.nan/0

ZeroDivisionError: float division by zero

In [53]:
0*np.nan

nan

# pandas automatically converts the None to NaN value

In [54]:
x=(np.arange(5,15,3))

In [55]:
x

array([ 5,  8, 11, 14])

In [56]:
type(x)

numpy.ndarray

In [62]:
x

0    (5, 8, 11, 14)
dtype: object

In [63]:
x=pd.Series(range(5,15,3))

In [64]:
x

0     5
1     8
2    11
3    14
dtype: int64

In [69]:
#%timeit#
#
##
#
#
#baki hai ise samajhana 
#

In [70]:
pd.Series([1,np.nan,None,pd.NA])

0       1
1     NaN
2    None
3    <NA>
dtype: object

In [77]:
pd.Series([1,np.nan,None,pd.NA],dtype=int32)

NameError: name 'int32' is not defined

In [78]:
pd.Series([1,"Hello",np.nan,"suno",None])

0        1
1    Hello
2      NaN
3     suno
4     None
dtype: object

In [87]:
import pandas as pd
x=pd.read_csv('netflix_data.csv')

In [88]:
x

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]

In [89]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   duration      7787 non-null   int64 
 9   description   7787 non-null   object
 10  genre         7787 non-null   object
dtypes: int64(2), object(9)
memory usage: 669.3+ KB


In [90]:
x.describe()

release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [91]:
x.isnull()

show_id   type  title  director   cast  country  date_added  \
0       False  False  False      True  False    False       False   
1       False  False  False     False  False    False       False   
2       False  False  False     False  False    False       False   
3       False  False  False     False  False    False       False   
4       False  False  False     False  False    False       False   
...       ...    ...    ...       ...    ...      ...         ...   
7782    False  False  False     False  False    False       False   
7783    False  False  False     False  False    False       False   
7784    False  False  False      True  False     True       False   
7785    False  False  False      True  False    False       False   
7786    False  False  False     False   True    False       False   

      release_year  duration  description  genre  
0            False     False        False  False  
1            False     False        False  False  
2            False     False        False  False  
3            False     False        False  False  
4            False     False        False  False  
...            ...       ...          ...    ...  
7782         False     False        False  False  
7783         False     False        False  False  
7784         False     False        False  False  
7785         False     False        False  False  
7786         False     False        False  False  

[7787 rows x 11 columns]

In [92]:
x.director.isnull()

0        True
1       False
2       False
3       False
4       False
        ...  
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool

In [93]:
x.director.isnull().sum()

2389

In [94]:
x.country.isnull().sum()

507

In [95]:
x.country.isna().sum()

507

In [97]:
x.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
duration           0
description        0
genre              0
dtype: int64

In [105]:
type(x)

pandas.core.frame.DataFrame

In [117]:
y=x['director'].dropna(inplace=True)

In [126]:
x.director.isnull().sum()

2389

In [130]:
x[['director']].dropna()

director
1     Jorge Michel Grau
2          Gilbert Chan
3           Shane Acker
4        Robert Luketic
5           Serdar Akar
...                 ...
7780       Shlok Sharma
7781       Peter Hewitt
7782        Josef Fares
7783        Mozez Singh
7786           Sam Dunn

[5398 rows x 1 columns]

In [133]:
x[['show_id']]

show_id
0         s1
1         s2
2         s3
3         s4
4         s5
...      ...
7782   s7783
7783   s7784
7784   s7785
7785   s7786
7786   s7787

[7787 rows x 1 columns]

In [124]:
x.dropna("director")

TypeError: DataFrame.dropna() takes 1 positional argument but 2 were given

In [119]:
x.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
duration           0
description        0
genre              0
dtype: int64

In [103]:
x.director.isnull()

0        True
1       False
2       False
3       False
4       False
        ...  
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool

In [134]:
x

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]

In [135]:
x.notnull()

show_id  type  title  director   cast  country  date_added  \
0        True  True   True     False   True     True        True   
1        True  True   True      True   True     True        True   
2        True  True   True      True   True     True        True   
3        True  True   True      True   True     True        True   
4        True  True   True      True   True     True        True   
...       ...   ...    ...       ...    ...      ...         ...   
7782     True  True   True      True   True     True        True   
7783     True  True   True      True   True     True        True   
7784     True  True   True     False   True    False        True   
7785     True  True   True     False   True     True        True   
7786     True  True   True      True  False     True        True   

      release_year  duration  description  genre  
0             True      True         True   True  
1             True      True         True   True  
2             True      True         True   True  
3             True      True         True   True  
4             True      True         True   True  
...            ...       ...          ...    ...  
7782          True      True         True   True  
7783          True      True         True   True  
7784          True      True         True   True  
7785          True      True         True   True  
7786          True      True         True   True  

[7787 rows x 11 columns]

In [136]:
x[x.notnull()]

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]